package org.firstinspires.ftc.teamcode.Utility;

import android.os.Environment;

import com.acmerobotics.dashboard.config.Config;

import org.opencv.core.Core;
import org.opencv.core.Mat;
import org.opencv.imgcodecs.Imgcodecs;
import org.opencv.imgproc.Imgproc;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

import static java.lang.Thread.sleep;

//import org.opencv.core.*;
//import org.opencv.imgproc.*;

/**
 * GripPipeline class.
 *
 * <p>An OpenCV pipeline generated by GRIP.
 *
 * @author GRIP
 */

@Config
public class BarCodeImageProcessor {

    private static BarCodeImageProcessor processor = new BarCodeImageProcessor();
    public static BarCodeImageProcessor getInstance(){
        return processor;
    }

    private int sizeThresh = 70000;
    private int lrTolerance = 10;
    public static double blurAmount = 10;
    int side =1;


    static {
//        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
    }

    public BarCodeImageProcessor() {
    }

    public ImageResult process(Mat input) {

        File path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        String filename = "Orig.jpg";
        File file = new File(path, filename);
        Imgcodecs.imwrite(file.toString(), input);

        //Rotate the Image

        Core.rotate(input, input, Core.ROTATE_90_CLOCKWISE);

        path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        filename = "Rotate.jpg";
        file = new File(path, filename);
        Imgcodecs.imwrite(file.toString(), input);

        List<Mat> bgr = new ArrayList<>();
        Core.split(input, bgr);
        Mat gray = bgr.get(1);
        path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        filename = "gray.jpg";
        file = new File(path, filename);
        Imgcodecs.imwrite(file.toString(), gray);

        //Crop the image
        Mat cropInput = gray;
        Mat cropOutput = new Mat();
        int widthLeft = (int) Math.round(input.width() * 0.36);
        int widthRight = (int) Math.round(input.width() * 0.77);
        int heightDown = (int) Math.round(input.height() * 0.62);
        int heightUp = (int) Math.round(input.height() * 0.75);
        cropOutput = cropInput.submat(heightDown,heightUp, widthLeft, widthRight);
        path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        filename = "Crop.jpg";
        file = new File(path, filename);
        Imgcodecs.imwrite(file.toString(), cropOutput);

        //Convert to black and white
        Mat bwInput = cropOutput;
        Mat bwOutput = new Mat();
        Imgproc.threshold(bwInput, bwOutput, 200, 255, Imgproc.THRESH_BINARY);

        path = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);
        filename = "Bw.jpg";
        file = new File(path, filename);
        Imgcodecs.imwrite(file.toString(), bwOutput);

        ImageResult imageResult = new ImageResult();
        imageResult.position = -1;

        int totalWhiteCount = 0;

        for (int i = 0; i < bwOutput.height(); i++) {
            for (int j = 0; j < bwOutput.width(); j++) {
                double pixelValue = bwOutput.get(i, j)[0];
                if(pixelValue == 255) {
                    totalWhiteCount ++;
                }
            }
        }

        if(side == 1)

        if(totalWhiteCount > 500) {
            imageResult.position = 1;
        }
        else if(totalWhiteCount > 100) {
            imageResult.position = 2;
        }
        else {
            imageResult.position = 3;
        }

        return imageResult;

    }

}


